const colors = {
  FORM_BACKGROUND_COLOR: "#F9FAFF",
  CABINET_CONTENT_BACKGROUND_COLOR: "#F9FAFF",
  CABINET_BACKGROUND_COLOR: "#E4EBFF",
  TEXT_COLOR: "#A1ABC9",
  TEXT_LINK_COLOR: `#7297FF`,
  TEXT_TITLE_COLOR: `#202225`,
  INPUT_COLOR: "#FFFFFF",
  ALERT_MESSAGE_COLOR: "#F6657F",
  ACTION_BUTTON_COLOR: `#7297FF`,
  INACTIVE_CABINET_TAB_COLOR: "#FFFFFF",
};

export const selectStyles = {
  option: (provided, state) => ({
    ...provided,
    height: "40px",
    background: state.isSelected ? "#F9FAFF" : "white",
    borderRadius: "6px",
    fontFamily: "'Poppins', sans-serif",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "15px",
    lineHeight: "130%",
    color: colors.TEXT_TITLE_COLOR,
  }),
  menuList: (provided) => ({
    ...provided,
    height: "128px",
    overflowY: "visible",
    "::-webkit-scrollbar": {
      width: "8px",
    },
    paddingLeft: "4px",
    paddingRight: "4px",
    overflowY: "scroll",
  }),
  control: (provided, state) => ({
    ...provided,
    paddingLeft: "16px",
    borderRadius: "8px",
    outline: "none",
    height: "100%",
    "&:hover": {},
    cursor: "pointer",
    boxShadow: "none",
    border: state.isFocused ? "1px solid #7297FF " : "1px solid #DCE0EC ",
  }),
  input: (provided) => ({
    ...provided,
    fontFamily: "'Poppins', sans-serif",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "15px",
    lineHeight: "130%",
  }),
  container: (provided) => ({
    ...provided,
    width: "624px",
    height: "56px",
    background: "#FFFFFF",
    boxSizing: "border-box",
    boxShadow: "0px 4px 32px rgba(218, 228, 255, 0.16)",
    borderRadius: "8px",
  }),
  indicatorSeparator: (provided) => ({
    ...provided,
    display: "none",
  }),
  placeholder: (provided) => ({
    ...provided,
    fontFamily: "'Poppins', sans-serif",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "17px",
    lineHeight: "24px",
    color: "#A1ABC9",
  }),
  singleValue: (provided) => ({
    ...provided,
    fontFamily: "'Poppins', sans-serif",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "15px",
    lineHeight: "130%",
  }),
};
